-- Using BigQuery to create a new table "annual_trip_2023" which would act as the merged table of data from January 2023 to October 2023.


SELECT
  ride_id,
  rideable_type,
  started_at,
  ended_at,
  start_station_name,
  start_station_id,
  end_station_id,
  member_casual,
  ride_length,
  day_of_week AS annual_trip_2023
FROM
  `cyclistic-data-405205.bike_sharing_data_2023.trip_202301`
UNION ALL
SELECT
  ride_id,
  rideable_type,
  started_at,
  ended_at,
  start_station_name,
  start_station_id,
  end_station_id,
  member_casual,
  ride_length,
  day_of_week
FROM
  `cyclistic-data-405205.bike_sharing_data_2023.trip_202302`
UNION ALL
SELECT
  ride_id,
  rideable_type,
  started_at,
  ended_at,
  start_station_name,
  start_station_id,
  end_station_id,
  member_casual,
  ride_length,
  day_of_week
FROM
  `cyclistic-data-405205.bike_sharing_data_2023.trip_202303`
UNION ALL
SELECT
  ride_id,
  rideable_type,
  started_at,
  ended_at,
  start_station_name,
  start_station_id,
  end_station_id,
  member_casual,
  ride_length,
  day_of_week
FROM
  `cyclistic-data-405205.bike_sharing_data_2023.trip_202304`
UNION ALL
SELECT
  ride_id,
  rideable_type,
  started_at,
  ended_at,
  start_station_name,
  start_station_id,
  end_station_id,
  member_casual,
  ride_length,
  day_of_week
FROM
  `cyclistic-data-405205.bike_sharing_data_2023.trip_202305`
UNION ALL
SELECT
  ride_id,
  rideable_type,
  started_at,
  ended_at,
  start_station_name,
  start_station_id,
  end_station_id,
  member_casual,
  ride_length,
  day_of_week
FROM
  `cyclistic-data-405205.bike_sharing_data_2023.trip_202306`
UNION ALL
SELECT
  ride_id,
  rideable_type,
  started_at,
  ended_at,
  start_station_name,
  start_station_id,
  end_station_id,
  member_casual,
  ride_length,
  day_of_week
FROM
  `cyclistic-data-405205.bike_sharing_data_2023.trip_202307`
UNION ALL
SELECT
  ride_id,
  rideable_type,
  started_at,
  ended_at,
  start_station_name,
  start_station_id,
  end_station_id,
  member_casual,
  ride_length,
  day_of_week
FROM
  `cyclistic-data-405205.bike_sharing_data_2023.trip_202308`
UNION ALL
SELECT
  ride_id,
  rideable_type,
  started_at,
  ended_at,
  start_station_name,
  start_station_id,
  end_station_id,
  member_casual,
  ride_length,
  day_of_week
FROM
  `cyclistic-data-405205.bike_sharing_data_2023.trip_202309`
UNION ALL
SELECT
  ride_id,
  rideable_type,
  started_at,
  ended_at,
  start_station_name,
  start_station_id,
  end_station_id,
  member_casual,
  ride_length,
  day_of_week
FROM
  `cyclistic-data-405205.bike_sharing_data_2023.trip_202310`
